apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30006


